Repository ICEI-PUC-Minas-PPLES-TI/plf-es-2024-1-ti1-0387200-primeira-ajuda-1, pull requests merged in 2024-04, with the labels that each got.

#2 refactor/complementa descrições referente as seções Objetivos, Justif…
  docs/README.md
Labels: enhancement

#3 refactor/Problema
  docs/README.md
Labels: enhancement

#4 Refactor/ referenciasSection
  docs/README.md
Labels: documentation, enhancement

#5 Refactor/Historias de Usuários.
  docs/README.md
Labels: documentation, enhancement

#6 refactor/fix Readme externo
  README.md
Labels: documentation, enhancement

#7 refactor/remove texto
  docs/README.md
Labels: documentation, enhancement

#8 Feat/personas
  docs/README.md
  docs/assets/images/personas/persona1.jpg
  docs/assets/images/personas/persona2.jpg
  docs/assets/images/personas/persona3.jpg
  docs/assets/images/personas/persona4.jpg
  docs/assets/images/personas/persona5.jpg
  docs/assets/images/personas/persona6.jpg
Labels: documentation, enhancement

#9 feat/utiliza_personas
  docs/README.md
Labels: documentation, enhancement

#10 refactor/utilizaPersonas
  docs/README.md
Labels: documentation, enhancement

#11 refactor
  docs/README.md
Labels: documentation, enhancement

#12 refector/
  docs/README.md
Labels: documentation, enhancement

#15 fix/
  docs/README.md
Labels: documentation, enhancement

#16 Fix/
  docs/README.md
Labels: documentation, enhancement

#17 refactor/
  docs/README.md
Labels: documentation, enhancement

#18 feat/userFlow
  docs/assets/images/userFlow/userFlowPrimeiraAjuda.jpg
Labels: documentation, enhancement

#20 fix/
  docs/index.html
Labels: enhancement, index
